export const SET_LIKELIST = 'SET-LIKELIST';

export const SET_INTHEATERS = 'SET_INTHEATERS';

export const SET_COMINGSOON = 'SET_COMINGSOON';

export const SET_TOP250 = 'SET_TOP250';

export const SET_MOVIEGRID = 'SET_MOVIEGRID';

export const CLEAR_MOVIEGRID = 'CLEAR_MOVIEGRID';

export const SET_DETAIL = 'SET_DETAIL';
